// Auto-generated. Do not edit!

// (in-package second_coursework.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RoomCheckGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.num_of_checks = null;
    }
    else {
      if (initObj.hasOwnProperty('num_of_checks')) {
        this.num_of_checks = initObj.num_of_checks
      }
      else {
        this.num_of_checks = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RoomCheckGoal
    // Serialize message field [num_of_checks]
    bufferOffset = _serializer.int32(obj.num_of_checks, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RoomCheckGoal
    let len;
    let data = new RoomCheckGoal(null);
    // Deserialize message field [num_of_checks]
    data.num_of_checks = _deserializer.int32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'second_coursework/RoomCheckGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'cd13df9789146541a04d078f7075089c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define goal
    int32 num_of_checks
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RoomCheckGoal(null);
    if (msg.num_of_checks !== undefined) {
      resolved.num_of_checks = msg.num_of_checks;
    }
    else {
      resolved.num_of_checks = 0
    }

    return resolved;
    }
};

module.exports = RoomCheckGoal;
