// Auto-generated. Do not edit!

// (in-package second_coursework.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RoomCheckResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.rule_break_count = null;
    }
    else {
      if (initObj.hasOwnProperty('rule_break_count')) {
        this.rule_break_count = initObj.rule_break_count
      }
      else {
        this.rule_break_count = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RoomCheckResult
    // Serialize message field [rule_break_count]
    bufferOffset = _arraySerializer.int32(obj.rule_break_count, buffer, bufferOffset, null);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RoomCheckResult
    let len;
    let data = new RoomCheckResult(null);
    // Deserialize message field [rule_break_count]
    data.rule_break_count = _arrayDeserializer.int32(buffer, bufferOffset, null)
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 4 * object.rule_break_count.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'second_coursework/RoomCheckResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1e2f74145994c14f07c573ef71b90ff4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #Define result
    int32[] rule_break_count
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RoomCheckResult(null);
    if (msg.rule_break_count !== undefined) {
      resolved.rule_break_count = msg.rule_break_count;
    }
    else {
      resolved.rule_break_count = []
    }

    return resolved;
    }
};

module.exports = RoomCheckResult;
