// Generated by gencpp from file second_coursework/MoveRobot.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_MOVEROBOT_H
#define SECOND_COURSEWORK_MESSAGE_MOVEROBOT_H

#include <ros/service_traits.h>


#include <second_coursework/MoveRobotRequest.h>
#include <second_coursework/MoveRobotResponse.h>


namespace second_coursework
{

struct MoveRobot
{

typedef MoveRobotRequest Request;
typedef MoveRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveRobot
} // namespace second_coursework


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::second_coursework::MoveRobot > {
  static const char* value()
  {
    return "d7f6bc17ab9cca7adaad06bf5bcb21cf";
  }

  static const char* value(const ::second_coursework::MoveRobot&) { return value(); }
};

template<>
struct DataType< ::second_coursework::MoveRobot > {
  static const char* value()
  {
    return "second_coursework/MoveRobot";
  }

  static const char* value(const ::second_coursework::MoveRobot&) { return value(); }
};


// service_traits::MD5Sum< ::second_coursework::MoveRobotRequest> should match
// service_traits::MD5Sum< ::second_coursework::MoveRobot >
template<>
struct MD5Sum< ::second_coursework::MoveRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::second_coursework::MoveRobot >::value();
  }
  static const char* value(const ::second_coursework::MoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_coursework::MoveRobotRequest> should match
// service_traits::DataType< ::second_coursework::MoveRobot >
template<>
struct DataType< ::second_coursework::MoveRobotRequest>
{
  static const char* value()
  {
    return DataType< ::second_coursework::MoveRobot >::value();
  }
  static const char* value(const ::second_coursework::MoveRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::second_coursework::MoveRobotResponse> should match
// service_traits::MD5Sum< ::second_coursework::MoveRobot >
template<>
struct MD5Sum< ::second_coursework::MoveRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::second_coursework::MoveRobot >::value();
  }
  static const char* value(const ::second_coursework::MoveRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_coursework::MoveRobotResponse> should match
// service_traits::DataType< ::second_coursework::MoveRobot >
template<>
struct DataType< ::second_coursework::MoveRobotResponse>
{
  static const char* value()
  {
    return DataType< ::second_coursework::MoveRobot >::value();
  }
  static const char* value(const ::second_coursework::MoveRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_MOVEROBOT_H
