// Generated by gencpp from file second_coursework/MoveRobotRequest.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_MOVEROBOTREQUEST_H
#define SECOND_COURSEWORK_MESSAGE_MOVEROBOTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_coursework
{
template <class ContainerAllocator>
struct MoveRobotRequest_
{
  typedef MoveRobotRequest_<ContainerAllocator> Type;

  MoveRobotRequest_()
    : room()  {
    }
  MoveRobotRequest_(const ContainerAllocator& _alloc)
    : room(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _room_type;
  _room_type room;





  typedef boost::shared_ptr< ::second_coursework::MoveRobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::MoveRobotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MoveRobotRequest_

typedef ::second_coursework::MoveRobotRequest_<std::allocator<void> > MoveRobotRequest;

typedef boost::shared_ptr< ::second_coursework::MoveRobotRequest > MoveRobotRequestPtr;
typedef boost::shared_ptr< ::second_coursework::MoveRobotRequest const> MoveRobotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::MoveRobotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_coursework::MoveRobotRequest_<ContainerAllocator1> & lhs, const ::second_coursework::MoveRobotRequest_<ContainerAllocator2> & rhs)
{
  return lhs.room == rhs.room;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_coursework::MoveRobotRequest_<ContainerAllocator1> & lhs, const ::second_coursework::MoveRobotRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::MoveRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::MoveRobotRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::MoveRobotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e497569192cccb82020c3a5c262721b9";
  }

  static const char* value(const ::second_coursework::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe497569192cccb82ULL;
  static const uint64_t static_value2 = 0x020c3a5c262721b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/MoveRobotRequest";
  }

  static const char* value(const ::second_coursework::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string room\n"
;
  }

  static const char* value(const ::second_coursework::MoveRobotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.room);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveRobotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::MoveRobotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_coursework::MoveRobotRequest_<ContainerAllocator>& v)
  {
    s << indent << "room: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.room);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_MOVEROBOTREQUEST_H
