// Generated by gencpp from file second_coursework/RoomCheckResult.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_ROOMCHECKRESULT_H
#define SECOND_COURSEWORK_MESSAGE_ROOMCHECKRESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_coursework
{
template <class ContainerAllocator>
struct RoomCheckResult_
{
  typedef RoomCheckResult_<ContainerAllocator> Type;

  RoomCheckResult_()
    : rule_break_count()  {
    }
  RoomCheckResult_(const ContainerAllocator& _alloc)
    : rule_break_count(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _rule_break_count_type;
  _rule_break_count_type rule_break_count;





  typedef boost::shared_ptr< ::second_coursework::RoomCheckResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::RoomCheckResult_<ContainerAllocator> const> ConstPtr;

}; // struct RoomCheckResult_

typedef ::second_coursework::RoomCheckResult_<std::allocator<void> > RoomCheckResult;

typedef boost::shared_ptr< ::second_coursework::RoomCheckResult > RoomCheckResultPtr;
typedef boost::shared_ptr< ::second_coursework::RoomCheckResult const> RoomCheckResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::RoomCheckResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::RoomCheckResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_coursework::RoomCheckResult_<ContainerAllocator1> & lhs, const ::second_coursework::RoomCheckResult_<ContainerAllocator2> & rhs)
{
  return lhs.rule_break_count == rhs.rule_break_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_coursework::RoomCheckResult_<ContainerAllocator1> & lhs, const ::second_coursework::RoomCheckResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::RoomCheckResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::RoomCheckResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::RoomCheckResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::RoomCheckResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::RoomCheckResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::RoomCheckResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::RoomCheckResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e2f74145994c14f07c573ef71b90ff4";
  }

  static const char* value(const ::second_coursework::RoomCheckResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e2f74145994c14fULL;
  static const uint64_t static_value2 = 0x07c573ef71b90ff4ULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::RoomCheckResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/RoomCheckResult";
  }

  static const char* value(const ::second_coursework::RoomCheckResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::RoomCheckResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"#Define result\n"
"int32[] rule_break_count\n"
;
  }

  static const char* value(const ::second_coursework::RoomCheckResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::RoomCheckResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rule_break_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoomCheckResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::RoomCheckResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_coursework::RoomCheckResult_<ContainerAllocator>& v)
  {
    s << indent << "rule_break_count[]" << std::endl;
    for (size_t i = 0; i < v.rule_break_count.size(); ++i)
    {
      s << indent << "  rule_break_count[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.rule_break_count[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_ROOMCHECKRESULT_H
