// Generated by gencpp from file second_coursework/RoomCheckGoal.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_ROOMCHECKGOAL_H
#define SECOND_COURSEWORK_MESSAGE_ROOMCHECKGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_coursework
{
template <class ContainerAllocator>
struct RoomCheckGoal_
{
  typedef RoomCheckGoal_<ContainerAllocator> Type;

  RoomCheckGoal_()
    : num_of_checks(0)  {
    }
  RoomCheckGoal_(const ContainerAllocator& _alloc)
    : num_of_checks(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_of_checks_type;
  _num_of_checks_type num_of_checks;





  typedef boost::shared_ptr< ::second_coursework::RoomCheckGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::RoomCheckGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RoomCheckGoal_

typedef ::second_coursework::RoomCheckGoal_<std::allocator<void> > RoomCheckGoal;

typedef boost::shared_ptr< ::second_coursework::RoomCheckGoal > RoomCheckGoalPtr;
typedef boost::shared_ptr< ::second_coursework::RoomCheckGoal const> RoomCheckGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::RoomCheckGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_coursework::RoomCheckGoal_<ContainerAllocator1> & lhs, const ::second_coursework::RoomCheckGoal_<ContainerAllocator2> & rhs)
{
  return lhs.num_of_checks == rhs.num_of_checks;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_coursework::RoomCheckGoal_<ContainerAllocator1> & lhs, const ::second_coursework::RoomCheckGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::RoomCheckGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::RoomCheckGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::RoomCheckGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cd13df9789146541a04d078f7075089c";
  }

  static const char* value(const ::second_coursework::RoomCheckGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd13df9789146541ULL;
  static const uint64_t static_value2 = 0xa04d078f7075089cULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/RoomCheckGoal";
  }

  static const char* value(const ::second_coursework::RoomCheckGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define goal\n"
"int32 num_of_checks\n"
;
  }

  static const char* value(const ::second_coursework::RoomCheckGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_of_checks);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoomCheckGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_coursework::RoomCheckGoal_<ContainerAllocator>& v)
  {
    s << indent << "num_of_checks: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_of_checks);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_ROOMCHECKGOAL_H
