// Generated by gencpp from file second_coursework/RoomCheckActionGoal.msg
// DO NOT EDIT!


#ifndef SECOND_COURSEWORK_MESSAGE_ROOMCHECKACTIONGOAL_H
#define SECOND_COURSEWORK_MESSAGE_ROOMCHECKACTIONGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <second_coursework/RoomCheckGoal.h>

namespace second_coursework
{
template <class ContainerAllocator>
struct RoomCheckActionGoal_
{
  typedef RoomCheckActionGoal_<ContainerAllocator> Type;

  RoomCheckActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  RoomCheckActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::second_coursework::RoomCheckGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct RoomCheckActionGoal_

typedef ::second_coursework::RoomCheckActionGoal_<std::allocator<void> > RoomCheckActionGoal;

typedef boost::shared_ptr< ::second_coursework::RoomCheckActionGoal > RoomCheckActionGoalPtr;
typedef boost::shared_ptr< ::second_coursework::RoomCheckActionGoal const> RoomCheckActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator1> & lhs, const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.goal_id == rhs.goal_id &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator1> & lhs, const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db056f719613f6dd90337e639f2c16de";
  }

  static const char* value(const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb056f719613f6ddULL;
  static const uint64_t static_value2 = 0x90337e639f2c16deULL;
};

template<class ContainerAllocator>
struct DataType< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_coursework/RoomCheckActionGoal";
  }

  static const char* value(const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"Header header\n"
"actionlib_msgs/GoalID goal_id\n"
"RoomCheckGoal goal\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: actionlib_msgs/GoalID\n"
"# The stamp should store the time at which this goal was requested.\n"
"# It is used by an action server when it tries to preempt all\n"
"# goals that were requested before a certain time\n"
"time stamp\n"
"\n"
"# The id provides a way to associate feedback and\n"
"# result message with specific goal requests. The id\n"
"# specified must be unique.\n"
"string id\n"
"\n"
"\n"
"================================================================================\n"
"MSG: second_coursework/RoomCheckGoal\n"
"# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define goal\n"
"int32 num_of_checks\n"
;
  }

  static const char* value(const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RoomCheckActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_coursework::RoomCheckActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_coursework::RoomCheckActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::second_coursework::RoomCheckGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_COURSEWORK_MESSAGE_ROOMCHECKACTIONGOAL_H
