(cl:defpackage second_coursework-srv
  (:use )
  (:export
   "MOVEROBOT"
   "<MOVEROBOT-REQUEST>"
   "MOVEROBOT-REQUEST"
   "<MOVEROBOT-RESPONSE>"
   "MOVEROBOT-RESPONSE"
   "YOLOLASTFRAME"
   "<YOLOLASTFRAME-REQUEST>"
   "YOLOLASTFRAME-REQUEST"
   "<YOLOLASTFRAME-RESPONSE>"
   "YOLOLASTFRAME-RESPONSE"
  ))

