(cl:defpackage second_coursework-msg
  (:use )
  (:export
   "<ROOMCHECKACTION>"
   "ROOMCHECKACTION"
   "<ROOMCHECKACTIONFEEDBACK>"
   "ROOMCHECKACTIONFEEDBACK"
   "<ROOMCHECKACTIONGOAL>"
   "ROOMCHECKACTIONGOAL"
   "<ROOMCHECKACTIONRESULT>"
   "ROOMCHECKACTIONRESULT"
   "<ROOMCHECKFEEDBACK>"
   "ROOMCHECKFEEDBACK"
   "<ROOMCHECKGOAL>"
   "ROOMCHECKGOAL"
   "<ROOMCHECKRESULT>"
   "ROOMCHECKRESULT"
  ))

