; Auto-generated. Do not edit!


(cl:in-package second_coursework-msg)


;//! \htmlinclude RoomCheckFeedback.msg.html

(cl:defclass <RoomCheckFeedback> (roslisp-msg-protocol:ros-message)
  ((pos
    :reader pos
    :initarg :pos
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point))
   (broken_rule
    :reader broken_rule
    :initarg :broken_rule
    :type cl:integer
    :initform 0))
)

(cl:defclass RoomCheckFeedback (<RoomCheckFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RoomCheckFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RoomCheckFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name second_coursework-msg:<RoomCheckFeedback> is deprecated: use second_coursework-msg:RoomCheckFeedback instead.")))

(cl:ensure-generic-function 'pos-val :lambda-list '(m))
(cl:defmethod pos-val ((m <RoomCheckFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader second_coursework-msg:pos-val is deprecated.  Use second_coursework-msg:pos instead.")
  (pos m))

(cl:ensure-generic-function 'broken_rule-val :lambda-list '(m))
(cl:defmethod broken_rule-val ((m <RoomCheckFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader second_coursework-msg:broken_rule-val is deprecated.  Use second_coursework-msg:broken_rule instead.")
  (broken_rule m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RoomCheckFeedback>) ostream)
  "Serializes a message object of type '<RoomCheckFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'pos) ostream)
  (cl:let* ((signed (cl:slot-value msg 'broken_rule)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RoomCheckFeedback>) istream)
  "Deserializes a message object of type '<RoomCheckFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'pos) istream)
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'broken_rule) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RoomCheckFeedback>)))
  "Returns string type for a message object of type '<RoomCheckFeedback>"
  "second_coursework/RoomCheckFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RoomCheckFeedback)))
  "Returns string type for a message object of type 'RoomCheckFeedback"
  "second_coursework/RoomCheckFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RoomCheckFeedback>)))
  "Returns md5sum for a message object of type '<RoomCheckFeedback>"
  "e0794b652eb087be218547842a4c7c69")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RoomCheckFeedback)))
  "Returns md5sum for a message object of type 'RoomCheckFeedback"
  "e0794b652eb087be218547842a4c7c69")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RoomCheckFeedback>)))
  "Returns full string definition for message of type '<RoomCheckFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define feedback~%geometry_msgs/Point pos~%int32 broken_rule~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RoomCheckFeedback)))
  "Returns full string definition for message of type 'RoomCheckFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define feedback~%geometry_msgs/Point pos~%int32 broken_rule~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RoomCheckFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'pos))
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RoomCheckFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RoomCheckFeedback
    (cl:cons ':pos (pos msg))
    (cl:cons ':broken_rule (broken_rule msg))
))
