; Auto-generated. Do not edit!


(cl:in-package second_coursework-msg)


;//! \htmlinclude RoomCheckGoal.msg.html

(cl:defclass <RoomCheckGoal> (roslisp-msg-protocol:ros-message)
  ((num_of_checks
    :reader num_of_checks
    :initarg :num_of_checks
    :type cl:integer
    :initform 0))
)

(cl:defclass RoomCheckGoal (<RoomCheckGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RoomCheckGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RoomCheckGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name second_coursework-msg:<RoomCheckGoal> is deprecated: use second_coursework-msg:RoomCheckGoal instead.")))

(cl:ensure-generic-function 'num_of_checks-val :lambda-list '(m))
(cl:defmethod num_of_checks-val ((m <RoomCheckGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader second_coursework-msg:num_of_checks-val is deprecated.  Use second_coursework-msg:num_of_checks instead.")
  (num_of_checks m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RoomCheckGoal>) ostream)
  "Serializes a message object of type '<RoomCheckGoal>"
  (cl:let* ((signed (cl:slot-value msg 'num_of_checks)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RoomCheckGoal>) istream)
  "Deserializes a message object of type '<RoomCheckGoal>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'num_of_checks) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RoomCheckGoal>)))
  "Returns string type for a message object of type '<RoomCheckGoal>"
  "second_coursework/RoomCheckGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RoomCheckGoal)))
  "Returns string type for a message object of type 'RoomCheckGoal"
  "second_coursework/RoomCheckGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RoomCheckGoal>)))
  "Returns md5sum for a message object of type '<RoomCheckGoal>"
  "cd13df9789146541a04d078f7075089c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RoomCheckGoal)))
  "Returns md5sum for a message object of type 'RoomCheckGoal"
  "cd13df9789146541a04d078f7075089c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RoomCheckGoal>)))
  "Returns full string definition for message of type '<RoomCheckGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define goal~%int32 num_of_checks~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RoomCheckGoal)))
  "Returns full string definition for message of type 'RoomCheckGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define goal~%int32 num_of_checks~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RoomCheckGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RoomCheckGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RoomCheckGoal
    (cl:cons ':num_of_checks (num_of_checks msg))
))
